### ISSUE TITLE
Add an image of all the icons in README

### ISSUE THREAD

**Issue by karuppiah7890** [alexbarbato/excalidraw-tanzu#1]
It would be cool to see all the icons in the README or at least some of the icons, more like a demo

**Comment by alexbarbato** [comment]
Great idea! Thanks

closed by https://github.com/alexbarbato/excalidraw-tanzu/commit/04ffcefc416e52fa568aa327edf7cced812bfcad

**Comment by karuppiah7890** [comment]
Sweet!
